# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: notrespond.OTAKUsVget
PackageVersion: 1.1.14
InstallerLocale: en-US
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: inno
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2026-10-05
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/notrespond/OTAKUsVget/releases/download/v1.1.14/OTAKUsVget-1.1.14-Setup.exe
  InstallerSha256: D302A299068EC41972B47B19376E6A6EEC39511AE97B0C4A87AD32089E3481E8
  AppsAndFeaturesEntries:
  - DisplayName: OTAKUsVget
    Publisher: OTAKUsVget
    DisplayVersion: 1.1.14
ManifestType: installer
ManifestVersion: 1.12.0
